trainer: teacher_forcing_dmd
ode_data_format: causvid
config_name: teacher_forcing_dmd_chunkwise

# ---------------------------------
# Raw Wan initialization
# ---------------------------------
# intentionally NO generator_ckpt

generator_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
generator_task: causal_video

model_kwargs:
  model_name: Wan2.1-T2V-1.3B
  timestep_shift: 5.0
  local_attn_size: 9
  sink_size: 3

timestep_shift: 5.0

num_frame_per_block: 3
independent_first_frame: false

# ---------------------------------
# ODE / rollout
# ---------------------------------
warmup_rollout_steps: 1000

denoising_step_list:
  - 1000
  - 750
  - 500
  - 250

warp_denoising_step: true

context_noise: 0

# ---------------------------------
# Optimization
# ---------------------------------
mixed_precision: true
gradient_checkpointing: true
sharding_strategy: hybrid_full

lr: 2.0e-6
lr_critic: 4.0e-07
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
ema_weight: 0.99
ema_start_step: 200
batch_size: 4
dfake_gen_update_ratio: 2
seed: 42

# ---------------------------------
# Data
# ---------------------------------
data_path: dataset/vidprom_sample_16k
max_pair: 16000
load_raw_video: false
data_store_ext: pt

# ---------------------------------
# Logging/checkpoints
# ---------------------------------
log_iters: 500
gc_interval: 20
console_print_interval: 1

wandb_host: https://api.wandb.ai
wandb_key: {not here}
wandb_entity: vlgunsdaddy
wandb_project: VideoAR


# ---------------------------------
# Additional configs
# ---------------------------------
real_name: Wan2.1-T2V-1.3B
fake_name: Wan2.1-T2V-1.3B
guidance_scale: 6.0
negative_prompt: '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'
image_or_video_shape:
- 1
- 21
- 16
- 60
- 104

